name: sandbox
description: A sanbox application where components are showcased and developed in an isolated way
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dashbook: ^0.1.7
  flame: ^1.1.1
  flame_forge2d: ^0.11.0
  flutter:
    sdk: flutter
  pinball_components:
    path: ../
  pinball_flame:
    path: ../../pinball_flame
  pinball_theme:
    path: ../../pinball_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
