name: share_repository
description: Repository to facilitate sharing scores.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^1.0.4
  test: ^1.19.2
  very_good_analysis: ^5.1.0
