name: platform_helper
description: Platform helper for Pinball application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0