name: leaderboard_repository
description: Repository to access leaderboard data in Firebase Cloud Firestore.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.4.3"

dependencies:
  cloud_firestore: ^5.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0