name: leaderboard_repository
description: Repository to access leaderboard data in Firebase Cloud Firestore.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.17.5
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0