name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy Development
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter App
        run: |
          flutter packages get
          flutter build web --target lib/main.dart --web-renderer canvaskit --release
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PINBALL_DEV }}"
          channelId: live
          projectId: pinball-dev
          target: ashehwkdkdjruejdnensjsjdne