name: geometry

on:
  push:
    paths:
      - "packages/geometry/**"
      - ".github/workflows/geometry.yaml"

  pull_request:
    paths:
      - "packages/geometry/**"
      - ".github/workflows/geometry.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/geometry
