name: pinball_audio

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/pinball_audio/**"
      - ".github/workflows/pinball_audio.yaml"

  pull_request:
    paths:
      - "packages/pinball_audio/**"
      - ".github/workflows/pinball_audio.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/pinball_audio
      coverage_excludes: "lib/gen/*.dart"
