name: share_repository

on:
  push:
    paths:
      - "packages/share_repository/**"
      - ".github/workflows/share_repository.yaml"

  pull_request:
    paths:
      - "packages/share_repository/**"
      - ".github/workflows/share_repository.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/share_repository
