name: spell_check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on: [pull_request]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
        uses: zwaldowski/cspell-action@v1
        with:
          paths: "**/*.*"
          config: .vscode/cspell.json